export const puzzles = [
  {
    id: 1,
    category: "Logic",
    question:
      "A man pushes his car to a hotel and tells the owner he's bankrupt. Why?",
    hint: "Think about a game played on a board.",
    answer: "He's playing Monopoly.",
    explanation: "This is a classic riddle about the board game Monopoly.",
  },
  {
    id: 2,
    category: "Math",
    question: "If you have 5 apples and take away 2, how many do you have?",
    hint: "Read carefully - 'you take away'.",
    answer: "2 apples",
    explanation: "You have 2 apples because those are the ones YOU took away.",
  },
  {
    id: 3,
    category: "Riddles",
    question:
      "What has keys but no locks, space but no room, and you can enter but can't go inside?",
    hint: "You might be using one to type.",
    answer: "A keyboard",
    explanation: "A keyboard has keys, a space bar, and an enter key.",
  },
  {
    id: 4,
    category: "Logic",
    question: "A farmer has 17 sheep. All but 9 die. How many are left?",
    hint: "'All but 9' is key.",
    answer: "9 sheep",
    explanation: "'All but 9' means 9 survived.",
  },
  {
    id: 5,
    category: "Math",
    question:
      "What three positive numbers give the same result when multiplied and added?",
    hint: "Small consecutive numbers.",
    answer: "1, 2, and 3",
    explanation: "1+2+3=6 and 1×2×3=6",
  },
  {
    id: 6,
    category: "Riddles",
    question: "The more you take, the more you leave behind. What am I?",
    hint: "Think about walking.",
    answer: "Footsteps",
    explanation: "More steps = more footprints left behind.",
  },
  {
    id: 7,
    category: "Logic",
    question:
      "A doctor gives you 3 pills, take one every half hour. How long will they last?",
    hint: "First pill is immediate.",
    answer: "1 hour",
    explanation: "Pill at 0:00, 0:30, and 1:00 = 1 hour total.",
  },
  {
    id: 8,
    category: "Math",
    question: "How can you make 7 even without math operations?",
    hint: "Think letters, not numbers.",
    answer: "Remove 'S' from SEVEN",
    explanation: "SEVEN without S = EVEN",
  },
  {
    id: 9,
    category: "Riddles",
    question:
      "What comes once in a minute, twice in a moment, never in a thousand years?",
    hint: "Look at the letters.",
    answer: "The letter M",
    explanation:
      "M appears once in minute, twice in moment, never in thousand years.",
  },
  {
    id: 10,
    category: "Logic",
    question: "You pass the person in 2nd place. What place are you?",
    hint: "You take their position.",
    answer: "Second place",
    explanation: "Passing 2nd means you become 2nd, not 1st.",
  },
  {
    id: 11,
    category: "Math",
    question:
      "A bat and ball cost $1.10. The bat costs $1 more than the ball. How much is the ball?",
    hint: "It's not 10 cents!",
    answer: "$0.05",
    explanation:
      "Ball=$0.05, Bat=$1.05. The bat is $1 more and total is $1.10.",
  },
  {
    id: 12,
    category: "Riddles",
    question: "What can travel around the world while staying in a corner?",
    hint: "Think about mail.",
    answer: "A stamp",
    explanation:
      "A stamp stays in the corner of an envelope but travels worldwide.",
  },
  {
    id: 13,
    category: "Logic",
    question:
      "If it takes 5 machines 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?",
    hint: "Think about rate per machine.",
    answer: "5 minutes",
    explanation:
      "Each machine makes 1 widget in 5 minutes, so 100 machines make 100 widgets in 5 minutes.",
  },
  {
    id: 14,
    category: "Math",
    question: "What is half of 2 + 2?",
    hint: "Order of operations matters.",
    answer: "3",
    explanation: "Half of 2 is 1, plus 2 equals 3. Not (2+2)/2=2.",
  },
  {
    id: 15,
    category: "Riddles",
    question: "What goes up but never comes down?",
    hint: "Happens to everyone every year.",
    answer: "Your age",
    explanation: "Age only increases, never decreases.",
  },
  {
    id: 16,
    category: "Logic",
    question:
      "You see a boat filled with people. It hasn't sunk, but you don't see a single person. Why?",
    hint: "What's the opposite of single?",
    answer: "Everyone is married",
    explanation: "Not a 'single' person - they're all married/coupled.",
  },
  {
    id: 17,
    category: "Math",
    question: "How many times can you subtract 10 from 100?",
    hint: "After the first time, what changes?",
    answer: "Once",
    explanation:
      "After subtracting 10 once (getting 90), you're no longer subtracting from 100.",
  },
  {
    id: 18,
    category: "Riddles",
    question: "What has a head and tail but no body?",
    hint: "You might flip it.",
    answer: "A coin",
    explanation: "Coins have heads and tails sides but no body.",
  },
  {
    id: 19,
    category: "Logic",
    question: "A rooster lays an egg on a barn roof. Which way does it roll?",
    hint: "Think about roosters carefully.",
    answer: "It doesn't - roosters don't lay eggs",
    explanation: "Roosters are male and don't lay eggs.",
  },
  {
    id: 20,
    category: "Math",
    question:
      "If you multiply all numbers on a phone keypad, what's the result?",
    hint: "Look at all the numbers.",
    answer: "0",
    explanation: "0 is on the keypad, and any number multiplied by 0 equals 0.",
  },
  {
    id: 21,
    category: "Logic",
    question:
      "Two fathers and two sons go fishing. They each catch one fish. Why do they only have 3 fish total?",
    hint: "There are only 3 people.",
    answer: "Grandfather, father, and son",
    explanation: "One person is both a father and a son.",
  },
  {
    id: 22,
    category: "Riddles",
    question: "What has hands but can't clap?",
    hint: "You check it to see the time.",
    answer: "A clock",
    explanation: "Clocks have hands but cannot clap.",
  },
  {
    id: 23,
    category: "Math",
    question: "What is 1+1 in binary?",
    hint: "Binary uses only 0 and 1.",
    answer: "10",
    explanation: "In binary, 1+1=10 (which is 2 in decimal).",
  },
  {
    id: 24,
    category: "Logic",
    question:
      "A woman shoots her husband, then holds him underwater for 5 minutes. Next, she hangs him. They go to dinner. How?",
    hint: "Think photography.",
    answer: "She's a photographer",
    explanation: "She shot a photo, developed it in water, and hung it to dry.",
  },
  {
    id: 25,
    category: "Riddles",
    question: "What building has the most stories?",
    hint: "Not about height.",
    answer: "A library",
    explanation: "Libraries have the most stories (books).",
  },
  {
    id: 26,
    category: "Math",
    question: "If 2's company and 3's a crowd, what are 4 and 5?",
    hint: "Simple arithmetic.",
    answer: "9",
    explanation: "4 + 5 = 9",
  },
  {
    id: 27,
    category: "Logic",
    question:
      "You're in a dark room with a candle, wood stove, and gas lamp. You have one match. What do you light first?",
    hint: "Think about the match itself.",
    answer: "The match",
    explanation: "You must light the match first before anything else.",
  },
  {
    id: 28,
    category: "Riddles",
    question: "What gets wetter the more it dries?",
    hint: "You use it after a shower.",
    answer: "A towel",
    explanation: "Towels get wet as they dry things.",
  },
  {
    id: 29,
    category: "Math",
    question: "A clerk in a butcher shop is 5'10\" tall. What does he weigh?",
    hint: "Read the question carefully.",
    answer: "Meat",
    explanation: "A butcher shop clerk weighs meat, not a number!",
  },
  {
    id: 30,
    category: "Logic",
    question:
      "If you overtake the last person in a race, what position are you in?",
    hint: "Think carefully about this.",
    answer: "Impossible",
    explanation: "You can't overtake the last person - they're already last!",
  },
  {
    id: 31,
    category: "Riddles",
    question: "What can you catch but not throw?",
    hint: "You don't want to catch this.",
    answer: "A cold",
    explanation: "You can catch a cold but cannot throw it.",
  },
  {
    id: 32,
    category: "Math",
    question: "How many months have 28 days?",
    hint: "Think about all months.",
    answer: "All 12 months",
    explanation: "Every month has at least 28 days.",
  },
  {
    id: 33,
    category: "Logic",
    question:
      "A man lives on the 10th floor. Every day he takes the elevator down to ground. Coming back, he goes to 7th floor then walks up. Why?",
    hint: "Think about his height.",
    answer: "He's too short to reach button 10",
    explanation: "He can only reach the button for floor 7.",
  },
  {
    id: 34,
    category: "Riddles",
    question: "What runs but never walks, has a mouth but never talks?",
    hint: "Think about geography.",
    answer: "A river",
    explanation: "Rivers run, have mouths, but don't walk or talk.",
  },
  {
    id: 35,
    category: "Math",
    question:
      "I am an odd number. Take away one letter and I become even. What am I?",
    hint: "Think of the word 'seven'.",
    answer: "Seven",
    explanation: "Remove the 's' from seven and you get 'even'.",
  },
  {
    id: 36,
    category: "Logic",
    question: "A girl fell off a 20-foot ladder but didn't get hurt. How?",
    hint: "Think about where she started.",
    answer: "She was on the bottom rung",
    explanation: "She was on the first step, close to the ground.",
  },
  {
    id: 37,
    category: "Riddles",
    question: "What has a neck but no head?",
    hint: "You might drink from it.",
    answer: "A bottle",
    explanation: "Bottles have necks but no heads.",
  },
  {
    id: 38,
    category: "Math",
    question: "Using only addition, how do you add eight 8's to get 1000?",
    hint: "Group them creatively.",
    answer: "888 + 88 + 8 + 8 + 8",
    explanation: "888 + 88 + 8 + 8 + 8 = 1000",
  },
  {
    id: 39,
    category: "Logic",
    question: "What word becomes shorter when you add two letters to it?",
    hint: "The word is 'short'.",
    answer: "Short",
    explanation: "Add 'er' to 'short' to make 'shorter'.",
  },
  {
    id: 40,
    category: "Riddles",
    question:
      "What has cities but no houses, forests but no trees, and water but no fish?",
    hint: "You use it for navigation.",
    answer: "A map",
    explanation:
      "Maps show cities, forests, and water but contain none of these things.",
  },
  {
    id: 41,
    category: "Math",
    question: "If there are 12 fish and half drown, how many are left?",
    hint: "Fish live in water.",
    answer: "12 fish",
    explanation: "Fish can't drown - they breathe underwater!",
  },
  {
    id: 42,
    category: "Logic",
    question: "What is always in front of you but can't be seen?",
    hint: "It hasn't happened yet.",
    answer: "The future",
    explanation: "The future is always ahead but invisible.",
  },
  {
    id: 43,
    category: "Riddles",
    question: "What goes through towns and over hills but never moves?",
    hint: "Cars drive on it.",
    answer: "A road",
    explanation: "Roads go everywhere but don't move themselves.",
  },
  {
    id: 44,
    category: "Math",
    question:
      "If you have a bowl with 6 apples and take away 4, how many do you have?",
    hint: "YOU take them away.",
    answer: "4 apples",
    explanation: "You have the 4 apples you took.",
  },
  {
    id: 45,
    category: "Logic",
    question: "What invention lets you look through a wall?",
    hint: "Every house has them.",
    answer: "A window",
    explanation: "Windows let you see through walls.",
  },
  {
    id: 46,
    category: "Riddles",
    question: "What belongs to you but others use it more?",
    hint: "People call you by it.",
    answer: "Your name",
    explanation: "Others use your name more than you do.",
  },
  {
    id: 47,
    category: "Math",
    question: "What 3 numbers give the same result added or multiplied?",
    hint: "1, 2, and 3.",
    answer: "1, 2, and 3",
    explanation: "1+2+3=6 and 1×2×3=6",
  },
  {
    id: 48,
    category: "Logic",
    question: "Feed me and I live, give me drink and I die. What am I?",
    hint: "It's hot and bright.",
    answer: "Fire",
    explanation: "Fire grows with fuel but dies with water.",
  },
  {
    id: 49,
    category: "Riddles",
    question: "What has legs but doesn't walk?",
    hint: "You sit on it.",
    answer: "A table or chair",
    explanation: "Furniture has legs but cannot walk.",
  },
  {
    id: 50,
    category: "Math",
    question: "What number can you subtract half from to get zero?",
    hint: "The number is 8.",
    answer: "8",
    explanation: "If you remove the top half of the digit 8, you get 0.",
  },
];
